"""BeamNG level package writer.

Produces a ZIP whose internal layout matches what `levels/<name>/` looks like
inside a working BeamNG.drive install. Drop the ZIP into

    %localappdata%/BeamNG.drive/<version>/mods/

and the level appears in the in-game level picker.

Minimum viable level (Phase 2):
    - terrain (.ter, terrain.json, materials)
    - LevelInfo + ScatterSky + TimeOfDay + sun
    - PlayerDropPoints with one SpawnSphere on the highest grid intersection
    - info.json (so the level shows up in the picker)
    - mainLevel.lua (BeamNG looks for it on level load)
    - flat grey terrain.png so the surface isn't an angry purple checkerboard

Later phases plug in: Phase 4 → real materials & terrain.png, Phase 3 → buildings,
Phase 5 → forest + decals + spawn heuristics.
"""
from __future__ import annotations

import io
import json
import math
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import numpy as np
from PIL import Image

from mapng_ai import config
from mapng_ai.assets.placeholder import write_unit_box_dae
from mapng_ai.pipeline.beamng_ter import write_ter
from mapng_ai.pipeline.placement import BuildingPlacement


# ---------------------------------------------------------------------------
# JSON snippets — keep these inlined so they're easy to read against the spec
# ---------------------------------------------------------------------------
def _info_json(level_name: str, side_m: float) -> dict:
    return {
        "title": level_name,
        "authors": "MapNG-AI",
        "description": f"Generated by MapNG-AI ({int(side_m)} m square)",
        "size": [int(side_m), int(side_m)],
        "previews": ["preview.png"],
        "defaultSpawnPointName": "spawn_default",
        "spawnPoints": [{
            "name": "Default",
            "objectname": "spawn_default",
            "preview": "preview.png",
            "translationId": "Default Spawnpoint",
        }],
    }


def _terrain_json(level_name: str, size_px: int, materials: list[str]) -> dict:
    return {
        "version": 9,
        "size": size_px,
        "datafile":        f"/levels/{level_name}/theTerrain.ter",
        "heightmapImage":  f"/levels/{level_name}/theTerrain.terrainheightmap.png",
        "heightMapSize": size_px * size_px,
        "heightMapItemSize": 2,
        "layerMapSize":  size_px * size_px,
        "layerMapItemSize": 1,
        "materials": materials,
        "binaryFormat": (
            "version(char), size(unsigned int), heightMap(heightMapSize * heightMapItemSize), "
            "layerMap(layerMapSize * layerMapItemSize), layerTextureMap(layerMapSize * layerMapItemSize), "
            "materialNames"
        ),
    }


def _terrain_materials_json(level_name: str, size_m: float) -> dict:
    return {
        "DefaultMaterial": {
            "class":        "TerrainMaterial",
            "internalName": "DefaultMaterial",
            "diffuseMap":   f"levels/{level_name}/art/terrains/terrain.png",
            "diffuseSize":  int(size_m),
            "groundmodelName": "GROUNDMODEL_ASPHALT1",
        },
    }


def _yaw_rotation_matrix(yaw: float) -> list[float]:
    c, s = math.cos(yaw), math.sin(yaw)
    return [c, -s, 0, s, c, 0, 0, 0, 1]


def _building_tsstatics(level_name: str, buildings: Sequence[BuildingPlacement]) -> list[dict]:
    out: list[dict] = []
    for b in buildings:
        sx, sy, sz = b.scale_xyz
        out.append({
            "class": "TSStatic",
            "name": f"bld_{b.osm_id}",
            "shapeName": f"/levels/{level_name}/{b.asset.shape_relpath}",
            # Box DAE is centred at origin, so lift by half the height
            "position": [b.x_m, b.y_m, b.z_m + sz / 2.0],
            "rotationMatrix": _yaw_rotation_matrix(b.yaw_rad),
            "scale": [sx, sy, sz],
            "instanceColor": [0.78, 0.74, 0.62, 1.0],
        })
    return out


def _level_objects(level_name: str, size_m: float, terrain_min_m: float, terrain_max_m: float,
                   spawn_x: float, spawn_y: float, spawn_z: float) -> list[dict]:
    half = size_m / 2
    return [
        {
            "class": "LevelInfo",
            "name": "theLevelInfo",
            "canvasClearColor": [0.4, 0.6, 0.8, 1.0],
            "fogDensity": 0.0001,
            "fogDensityOffset": 0,
            "fogAtmosphereHeight": 1000,
            "globalEnviromentMap": "BNG_Sky_02_cubemap",
            "gravity": -9.81,
            "nearClip": 0.1,
            "visibleDistance": 4000,
        },
        {
            "class": "TimeOfDay",
            "name": "tod",
            "startTime": 0.20,
        },
        {
            "class": "ScatterSky",
            "name": "sunsky",
            "ambientScaleGradientFile": "art/sky_gradients/default/gradient_ambient.png",
            "colorizeGradientFile":     "art/sky_gradients/default/gradient_colorize.png",
            "fogScaleGradientFile":     "art/sky_gradients/default/gradient_fog.png",
            "sunScaleGradientFile":     "art/sky_gradients/default/gradient_sunscale.png",
            "enableFogFallBack": False,
            "shadowDistance": 1500,
            "skyBrightness": 40,
            "texSize": 2048,
        },
        {
            "class": "Sun",
            "name": "theSun",
            "azimuth": 230,
            "elevation": 35,
            "color": [1.0, 0.95, 0.85, 1.0],
            "ambient": [0.30, 0.32, 0.35, 1.0],
            "brightness": 1.0,
        },
        {
            "class": "SimGroup",
            "name": "Other",
            "children": [
                {
                    "class": "TerrainBlock",
                    "name": "theTerrain",
                    "terrainFile": f"/levels/{level_name}/theTerrain.terrain.json",
                    "position":  [-half, -half, terrain_min_m],
                    "scale":     [1, 1, 1],
                    "castShadows": True,
                    "squareSize": size_m / 2048,  # metres per heightmap texel
                },
            ],
        },
    ]


def _spawn_objects(spawn_x: float, spawn_y: float, spawn_z: float) -> list[dict]:
    return [{
        "class": "SpawnSphere",
        "name": "spawn_default",
        "dataBlock": "SpawnSphereMarker",
        "position": [spawn_x, spawn_y, spawn_z],
        "rotationMatrix": [1, 0, 0, 0, 1, 0, 0, 0, 1],
        "radius": 5,
        "spawnTransform": "0 0 0 0 0 1 0",
    }]


def _mission_group(level_name: str, size_m: float, terrain_min_m: float, terrain_max_m: float,
                   spawn_xyz: tuple[float, float, float],
                   buildings: Sequence[BuildingPlacement]) -> dict:
    sx, sy, sz = spawn_xyz
    children = [
        {
            "class": "SimGroup", "name": "PlayerDropPoints",
            "children": _spawn_objects(sx, sy, sz),
        },
        {
            "class": "SimGroup", "name": "Level_objects",
            "children": _level_objects(level_name, size_m, terrain_min_m, terrain_max_m, sx, sy, sz),
        },
    ]
    if buildings:
        children.append({
            "class": "SimGroup",
            "name": "buildings",
            "children": _building_tsstatics(level_name, buildings),
        })
    return {"class": "SimGroup", "name": "MissionGroup", "children": children}


def _items_level_root(level_name: str, size_m: float, t_min: float, t_max: float,
                      spawn: tuple[float, float, float],
                      buildings: Sequence[BuildingPlacement]) -> dict:
    return {
        "class": "SimGroup",
        "name": "MissionCleanup",
        "children": [_mission_group(level_name, size_m, t_min, t_max, spawn, buildings)],
    }


# ---------------------------------------------------------------------------
# Helpers — heightmap PNG (visualisation) + flat terrain.png placeholder
# ---------------------------------------------------------------------------
def _heightmap_visual_png(heightmap_m: np.ndarray) -> bytes:
    min_m = heightmap_m.min(); max_m = heightmap_m.max()
    rng = max(max_m - min_m, 1e-6)
    quant = ((heightmap_m - min_m) / rng * 65535).clip(0, 65535).astype("<u2")
    img = Image.fromarray(quant[::-1, :], mode="I;16")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def _flat_terrain_png(size: int = 1024, rgb: tuple[int, int, int] = (90, 110, 70)) -> bytes:
    img = Image.new("RGB", (size, size), rgb)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def _solid_preview_png(size: int = 256) -> bytes:
    img = Image.new("RGB", (size, size), (40, 60, 90))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Top-level export
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class LevelPackage:
    zip_path: Path
    level_name: str
    spawn_xyz: tuple[float, float, float]
    terrain_min_m: float
    terrain_max_m: float


def write_level_package(
    *,
    level_name: str,
    heightmap_m: np.ndarray,
    side_m: float,
    out_dir: Path,
    layer_map: np.ndarray | None = None,
    material_names: list[str] | None = None,
    terrain_png_bytes: bytes | None = None,
    buildings: Sequence[BuildingPlacement] = (),
) -> LevelPackage:
    out_dir.mkdir(parents=True, exist_ok=True)
    zip_path = out_dir / f"{level_name}.zip"

    size_px = heightmap_m.shape[0]
    if heightmap_m.shape[1] != size_px:
        raise ValueError("heightmap must be square")

    materials = material_names or ["DefaultMaterial"]

    # Write the .ter to a temp buffer
    ter_path = out_dir / "_tmp_theTerrain.ter"
    t_min, t_max = write_ter(heightmap_m, ter_path, layer_map=layer_map, material_names=materials)
    ter_bytes = ter_path.read_bytes()
    ter_path.unlink()

    # Spawn point: centre of terrain, lifted to terrain height + 3 m so the car
    # doesn't spawn underground. BeamNG terrain space puts the SW corner at
    # `position` from level_objects; with TerrainBlock.position = (-half, -half, min),
    # the centre in world space is (0, 0, min + height_at_centre).
    cy, cx = size_px // 2, size_px // 2
    centre_h = float(heightmap_m[cy, cx])
    spawn_xyz = (0.0, 0.0, centre_h + 3.0)

    base = f"levels/{level_name}"

    files: list[tuple[str, bytes]] = []
    def w(path: str, data: bytes | str) -> None:
        if isinstance(data, str):
            data = data.encode("utf-8")
        files.append((path, data))

    # Top-level metadata
    w(f"{base}/info.json", json.dumps(_info_json(level_name, side_m), indent=2))
    w(f"{base}/mainLevel.lua",
      "-- MapNG-AI generated level\n-- (intentionally empty — Phase 2 minimum)\n")
    w(f"{base}/preview.png", _solid_preview_png())

    # Terrain
    w(f"{base}/theTerrain.ter", ter_bytes)
    w(f"{base}/theTerrain.terrain.json",
      json.dumps(_terrain_json(level_name, size_px, materials), indent=2))
    w(f"{base}/theTerrain.terrainheightmap.png", _heightmap_visual_png(heightmap_m))

    # Materials + base diffuse texture
    w(f"{base}/art/terrains/main.materials.json",
      json.dumps(_terrain_materials_json(level_name, side_m), indent=2))
    w(f"{base}/art/terrains/terrain.png", terrain_png_bytes or _flat_terrain_png())

    # Building shape (single shared box.dae). Cache it in mapng_ai/cache/shapes/
    # so we don't trip Windows file locks via tempfile cleanup.
    if buildings:
        shape_cache = config.CACHE_DIR / "shapes"
        shape_cache.mkdir(parents=True, exist_ok=True)
        box_path = shape_cache / "box.dae"
        write_unit_box_dae(box_path)
        w(f"{base}/art/shapes/buildings/box.dae", box_path.read_bytes())

    # Scene graph (the SimGroup tree BeamNG loads)
    items = _items_level_root(level_name, side_m, t_min, t_max, spawn_xyz, buildings)
    w(f"{base}/main/items.level.json", json.dumps(items, indent=2))

    # Build the ZIP
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for path, data in files:
            zf.writestr(path, data)

    return LevelPackage(
        zip_path=zip_path,
        level_name=level_name,
        spawn_xyz=spawn_xyz,
        terrain_min_m=t_min,
        terrain_max_m=t_max,
    )
