"""BeamNG level package writer.

Produces a ZIP whose internal layout matches what `levels/<name>/` looks like
inside a working BeamNG.drive install. Drop the ZIP into

    %localappdata%/BeamNG.drive/<version>/mods/

and the level appears in the in-game level picker.

Key facts about BeamNG terrain:
  - World width = size_px * squareSize  (squareSize MUST be set or terrain is wrong scale)
  - TerrainBlock position is the SW corner in world space
  - maxHeight is the full height range (max_elev - min_elev), NOT the absolute max
  - TerrainMaterial has NO blendMap field; layer blending comes from .ter layerMap
  - Material paths must include the file extension
"""
from __future__ import annotations

import io
import json
import math
import os
import uuid
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import numpy as np
from PIL import Image

from mapng_ai import config
from mapng_ai.assets.placeholder import (
    write_hedge_dae, write_pitched_dae, write_tree_dae, write_wall_dae,
    write_fence_dae, write_gate_dae,
)
from mapng_ai.pipeline.beamng_ter import write_ter
from mapng_ai.pipeline.decal_roads import (
    DecalRoad, write_road_decal_texture, write_drive_decal_texture,
)
from mapng_ai.pipeline.foliage import FoliageResult, HedgeSegment, TreePlacement
from mapng_ai.pipeline.placement import BuildingPlacement
from mapng_ai.pipeline.splatting import SplatResult


# ---------------------------------------------------------------------------
# Metadata files
# ---------------------------------------------------------------------------

def _info_json(level_name: str, side_m: float) -> dict:
    return {
        "title": level_name,
        "authors": "MapNG-AI",
        "description": f"Generated by MapNG-AI ({int(side_m)} m square)",
        "size": [int(side_m), int(side_m)],
        "previews": ["preview.png"],
        "defaultSpawnPointName": "spawn_default",
        "spawnPoints": [{
            "name": "Default",
            "objectname": "spawn_default",
            "preview": "preview.png",
            "translationId": "Default Spawnpoint",
        }],
    }


def _terrain_json(level_name: str, size_px: int, side_m: float, materials: list[str]) -> dict:
    """terrain.json descriptor for the .ter binary.

    squareSize (meters per pixel) is critical — without it BeamNG defaults
    to 1 m/px and the terrain renders at size_px × size_px meters instead
    of the intended side_m × side_m meters.
    """
    square_size = side_m / size_px
    return {
        "version": 9,
        "size": size_px,
        "squareSize": square_size,
        "datafile": f"levels/{level_name}/theTerrain.ter",
        "heightmapImage": f"levels/{level_name}/theTerrain.terrainheightmap.png",
        "heightMapSize": size_px * size_px,
        "heightMapItemSize": 2,
        "layerMapSize": size_px * size_px,
        "layerMapItemSize": 1,
        "materials": materials,
        "binaryFormat": (
            "version(char), size(unsigned int), heightMap(heightMapSize * heightMapItemSize), "
            "layerMap(layerMapSize * layerMapItemSize), "
            "layerTextureMap(layerMapSize * layerMapItemSize), materialNames"
        ),
    }


def _terrain_materials_json(level_name: str, side_m: float,
                             splat: SplatResult | None = None) -> dict:
    """TerrainMaterial definitions.

    Rules:
      - NO blendMap field — layer blending is encoded in the .ter layerMap binary,
        not as a per-material image reference.  Adding blendMap causes BeamNG to
        fail loading the asset reference and leaves the surface untextured.
      - diffuseMap MUST include the file extension.
      - mapTo must match the dict key so BeamNG resolves the material by name.
      - diffuseSize is the world-space tile size in meters (4 m = fine detail).
    """
    _GROUNDMODELS = {
        "asphalt":  "ASPHALT",
        "concrete": "ASPHALT",
        "lawn":     "GRASS",
        "pasture":  "GRASS",
        "earth":    "DIRT",
        "gravel":   "GRAVEL",
        "water":    "ASPHALT",
        "forest":   "GRASS",
    }

    if splat is None:
        return {
            "DefaultMaterial": {
                "mapTo": "DefaultMaterial",
                "class": "TerrainMaterial",
                "internalName": "DefaultMaterial",
                "diffuseMap": f"levels/{level_name}/art/terrains/terrain.png",
                "diffuseSize": int(side_m),
                "groundmodelName": "ASPHALT",
            },
        }

    out: dict = {}
    for layer in splat.layers:
        key = layer.cls.key
        ext = layer.diffuse_path.suffix.lower()
        mat: dict = {
            "mapTo": f"mat_{key}",
            "class": "TerrainMaterial",
            "internalName": f"mat_{key}",
            "diffuseMap": f"levels/{level_name}/art/terrains/diffuse_{key}{ext}",
            "diffuseSize": 4,
            "groundmodelName": _GROUNDMODELS.get(key, "GRASS"),
        }
        if layer.normal_path is not None:
            ne = layer.normal_path.suffix.lower()
            mat["normalMap"] = f"levels/{level_name}/art/terrains/normal_{key}{ne}"
        if layer.roughness_path is not None:
            re_ = layer.roughness_path.suffix.lower()
            mat["specularMap"] = f"levels/{level_name}/art/terrains/rough_{key}{re_}"
            mat["specularPower"] = 16
        out[f"mat_{key}"] = mat
    return out


# ---------------------------------------------------------------------------
# mainLevel.lua
# ---------------------------------------------------------------------------

def _main_level_lua(level_name: str, foreign_levels: list[str]) -> str:
    if foreign_levels:
        levels_lua = "{\n" + "\n".join(f"  '{name}'," for name in foreign_levels) + "\n}"
    else:
        levels_lua = "{}"
    return (
        "-- MapNG-AI generated level\n"
        "local M = {}\n"
        "\n"
        f"local foreignLevels = {levels_lua}\n"
        "\n"
        "local function loadMaterialsFromDir(dir)\n"
        "  local files = FS:findFiles(dir, '*.materials.json', -1, true, false)\n"
        "  for _, filename in ipairs(files) do\n"
        "    loadJsonMaterialsFile(filename)\n"
        "  end\n"
        "end\n"
        "\n"
        "local function onClientStartMission(levelPath)\n"
        f"  loadMaterialsFromDir('/levels/{level_name}/art/')\n"
        "  for _, name in ipairs(foreignLevels) do\n"
        "    loadMaterialsFromDir('/levels/' .. name .. '/art/')\n"
        "  end\n"
        "end\n"
        "\n"
        "local function onUpdate() end\n"
        "\n"
        "M.onClientStartMission = onClientStartMission\n"
        "M.onUpdate = onUpdate\n"
        "return M\n"
    )


# ---------------------------------------------------------------------------
# Road materials
# ---------------------------------------------------------------------------

def _road_materials_json(level_name: str) -> dict:
    def _mat(name: str, tex_path: str) -> dict:
        return {
            "mapTo": name,
            "class": "Material",
            "translucent": True,
            "translucentBlendOp": "PreMulAlpha",
            "alphaRef": 0,
            "Stages": [
                {
                    "baseColorMap": tex_path,
                    "baseColorFactor": [1.0, 1.0, 1.0, 1.0],
                },
                {}, {}, {},
            ],
        }

    return {
        "MapNG_RoadDecal": _mat(
            "MapNG_RoadDecal",
            f"levels/{level_name}/art/road/road_decal.png",
        ),
        "MapNG_DriveDecal": _mat(
            "MapNG_DriveDecal",
            f"levels/{level_name}/art/road/drive_decal.png",
        ),
    }


# ---------------------------------------------------------------------------
# Scene-graph helpers
# ---------------------------------------------------------------------------

def _yaw_rotation_matrix(yaw: float) -> list[float]:
    c, s = math.cos(yaw), math.sin(yaw)
    return [c, -s, 0, s, c, 0, 0, 0, 1]


def _shape_name(level_name: str, shape_relpath: str) -> str:
    if shape_relpath.startswith("levels/"):
        return f"/{shape_relpath}"
    return f"/levels/{level_name}/{shape_relpath}"


def _building_tsstatics(level_name: str, buildings: Sequence[BuildingPlacement]) -> list[dict]:
    out = []
    for b in buildings:
        sx, sy, sz = b.scale_xyz
        out.append({
            "class": "TSStatic",
            "name": f"bld_{b.osm_id}",
            "shapeName": _shape_name(level_name, b.asset.shape_relpath),
            "position": [b.x_m, b.y_m, b.z_m],
            "rotationMatrix": _yaw_rotation_matrix(b.yaw_rad),
            "scale": [sx, sy, sz],
        })
    return out


def _tree_tsstatics(level_name: str, trees: Sequence[TreePlacement]) -> list[dict]:
    out = []
    for i, t in enumerate(trees):
        sx, sy, sz = t.scale_xyz
        out.append({
            "class": "TSStatic",
            "name": f"tree_{i}",
            "shapeName": _shape_name(level_name, t.shape_relpath),
            "position": [t.x, t.y, t.z],
            "rotationMatrix": _yaw_rotation_matrix(t.yaw),
            "scale": [sx, sy, sz],
        })
    return out


def _hedge_tsstatics(level_name: str, hedges: Sequence[HedgeSegment]) -> list[dict]:
    import random as _r
    out = []
    hedge_shape = f"/levels/{level_name}/art/shapes/foliage/hedge.dae"
    wall_shape  = f"/levels/{level_name}/art/shapes/foliage/wall.dae"
    fence_shape = f"/levels/{level_name}/art/shapes/foliage/fence.dae"
    gate_shape  = f"/levels/{level_name}/art/shapes/foliage/gate.dae"
    for i, h in enumerate(hedges):
        seed = (i * 2654435761) ^ hash((round(h.x, 1), round(h.y, 1)))
        rng = _r.Random(seed & 0xFFFFFFFF)
        mat = getattr(h, "material", "hedge") or "hedge"

        if mat in ("wall", "fence", "gate"):
            shape = {"wall": wall_shape, "fence": fence_shape, "gate": gate_shape}[mat]
            out.append({
                "class": "TSStatic",
                "name": f"{mat}_{i}",
                "shapeName": shape,
                "position": [h.x, h.y, h.z],
                "rotationMatrix": _yaw_rotation_matrix(h.yaw + rng.uniform(-0.04, 0.04)),
                "scale": [
                    h.length_m * rng.uniform(0.97, 1.03),
                    h.width_m  * rng.uniform(0.95, 1.10),
                    h.height_m * rng.uniform(0.92, 1.08),
                ],
            })
            continue

        n = max(3, min(6, int(round(h.length_m / 0.9))))
        cos_y, sin_y = math.cos(h.yaw), math.sin(h.yaw)
        for k in range(n):
            t = (k + 0.5) / n + rng.uniform(-0.06, 0.06)
            t = max(0.02, min(0.98, t))
            along = (t - 0.5) * h.length_m
            lateral = rng.uniform(-h.width_m * 0.35, h.width_m * 0.35)
            bx = h.x + cos_y * along - sin_y * lateral
            by = h.y + sin_y * along + cos_y * lateral
            out.append({
                "class": "TSStatic",
                "name": f"hedge_{i}_{k}",
                "shapeName": hedge_shape,
                "position": [bx, by, h.z],
                "rotationMatrix": _yaw_rotation_matrix(h.yaw + rng.uniform(-math.pi, math.pi)),
                "scale": [
                    h.width_m  * rng.uniform(1.0, 1.6),
                    h.width_m  * rng.uniform(1.0, 1.6),
                    h.height_m * rng.uniform(0.85, 1.15),
                ],
            })
    return out


def _decal_roads_objects(roads: Sequence[DecalRoad]) -> list[dict]:
    out = []
    for road in roads:
        is_drive = getattr(road, "material", "asphalt") == "dirt"
        material = "MapNG_DriveDecal" if is_drive else "MapNG_RoadDecal"
        prefix = "drive" if is_drive else "road"
        first = road.nodes_xyz[0]
        out.append({
            "class": "DecalRoad",
            "name": f"{prefix}_{road.osm_id}",
            "material": material,
            "position": [first[0], first[1], first[2]],
            "nodes": [[x, y, z, road.width_m] for (x, y, z) in road.nodes_xyz],
            "drivability": 0.6 if is_drive else 1.0,
            "renderPriority": 8 if is_drive else 10,
            "breakAngle": 3,
            "distanceFade": [200, 50],
            "startEndFade": [5, 5],
            "textureLength": 5.0 if is_drive else 12.0,
            "improvedSpline": True,
            "smoothness": 0.5,
            "useSubdivisions": True,
        })
    return out


def _level_objects(level_name: str, size_m: float, size_px: int,
                   terrain_min_m: float, terrain_max_m: float,
                   water_z: float | None = None) -> list[dict]:
    half = size_m / 2
    square_size = size_m / size_px
    # maxHeight = full height range so BeamNG maps uint16 → world-space metres correctly.
    # Using absolute max_m would exaggerate terrain by ~10–20× for NI topography.
    max_height = max(1.0, float(terrain_max_m - terrain_min_m))
    terrain_block = {
        "class": "TerrainBlock",
        "name": "theTerrain",
        # path WITHOUT leading slash — matches community mod convention
        "terrainFile": f"levels/{level_name}/theTerrain.ter",
        # SW corner: terrain extends from here by size_px * squareSize in X and Y
        "position": [-half, -half, terrain_min_m],
        # squareSize = metres per heightmap pixel — critical for correct world scale
        "squareSize": square_size,
        "maxHeight": max_height,
        "castShadows": True,
    }
    children = [terrain_block]
    if water_z is not None:
        children.append({
            "class": "WaterPlane",
            "name": "theWater",
            "position": [0.0, 0.0, water_z],
        })
    return [
        {
            "class": "LevelInfo",
            "name": "theLevelInfo",
            "canvasClearColor": [1, 1, 1, 255],
            "enabled": "1",
            "fogColor": [0.66, 0.88, 0.99, 1],
            "fogDensity": 0.0005,
            "fogDensityOffset": 2,
            "fogAtmosphereHeight": 800,
            "globalEnviromentMap": "BNG_Sky_02_cubemap",
            "gravity": -9.81,
            "soundAmbience": "AudioAmbienceDefault",
            "visibleDistance": 4500,
        },
        {
            "class": "TimeOfDay",
            "name": "tod",
            "axisTilt": 20,
            "play": False,
            "startTime": 0.40,
            "time": 0.40,
        },
        {
            "class": "ScatterSky",
            "name": "sunsky",
            "azimuth": 230,
            "elevation": 45,
            "ambientScale":      [0.55, 0.55, 0.55, 1],
            "colorize":          [1, 1, 1, 1],
            "colorizeAmount":    0,
            "fogScale":          [1, 1, 1, 1],
            "sunScale":          [1, 1, 1, 1],
            "enableFogFallBack": False,
            "exposure":          1.0,
            "flareScale": 1,
            "flareType": "BNG_SunFlare_3",
            "lastSplitTerrainOnly": True,
            "logWeight": 0.99,
            "mieScattering": 0.000363,
            "rayleighScattering": 0.01,
            "shadowDistance": 1600,
            "shadowSoftness": 0.2,
            "skyBrightness": 12,
            "texSize": 1024,
        },
        {
            "class": "SimGroup",
            "name": "Other",
            "childs": children,
        },
    ]


def _spawn_objects(spawn_x: float, spawn_y: float, spawn_z: float) -> list[dict]:
    return [{
        "class": "SpawnSphere",
        "name": "spawn_default",
        "dataBlock": "SpawnSphereMarker",
        "position": [spawn_x, spawn_y, spawn_z],
        "rotationMatrix": [1, 0, 0, 0, 1, 0, 0, 0, 1],
        "enabled": "1",
        "homingCount": "0",
        "indoorWeight": "1",
        "isAIControlled": "0",
        "lockCount": "0",
        "outdoorWeight": "1",
        "radius": 1,
        "sphereWeight": "1",
        "spawnTransform": "0 0 0 0 0 1 0",
    }]


def _mission_group(
    level_name: str,
    size_m: float,
    size_px: int,
    terrain_min_m: float,
    terrain_max_m: float,
    spawn_xyz: tuple[float, float, float],
    buildings: Sequence[BuildingPlacement],
    foliage: FoliageResult | None,
    roads: Sequence[DecalRoad],
    water_z: float | None = None,
) -> dict:
    sx, sy, sz = spawn_xyz
    children = [
        {
            "class": "SimGroup",
            "name": "PlayerDropPoints",
            "childs": _spawn_objects(sx, sy, sz),
        },
        {
            "class": "SimGroup",
            "name": "Level_objects",
            "childs": _level_objects(level_name, size_m, size_px,
                                     terrain_min_m, terrain_max_m, water_z=water_z),
        },
    ]
    if buildings:
        children.append({
            "class": "SimGroup",
            "name": "buildings",
            "childs": _building_tsstatics(level_name, buildings),
        })
    if foliage and foliage.trees:
        children.append({
            "class": "SimGroup",
            "name": "trees",
            "childs": _tree_tsstatics(level_name, foliage.trees),
        })
    if foliage and foliage.hedges:
        children.append({
            "class": "SimGroup",
            "name": "hedges",
            "childs": _hedge_tsstatics(level_name, foliage.hedges),
        })
    if roads:
        children.append({
            "class": "SimGroup",
            "name": "Decal_Roads",
            "childs": _decal_roads_objects(roads),
        })
    return {"class": "SimGroup", "name": "MissionGroup", "childs": children}


# ---------------------------------------------------------------------------
# NDJSON scene-tree emitter (vanilla BeamNG format)
# ---------------------------------------------------------------------------

def _emit_ndjson_tree(scene_root: dict, base_main_path: str, write_func) -> None:
    """Walk a nested SimGroup tree and write per-group items.level.json files."""

    def _ensure_pid(obj: dict) -> None:
        if "persistentId" not in obj:
            obj["persistentId"] = str(uuid.uuid4())

    def _write_group(group: dict, path_segments: list[str]) -> None:
        group_name = group["name"]
        children = group.get("childs", []) or []
        rel_dir = "/".join(path_segments + [group_name])
        full_path = f"{base_main_path}/{rel_dir}/items.level.json"
        lines = []
        for child in children:
            _ensure_pid(child)
            child_copy = {k: v for k, v in child.items() if k != "childs"}
            child_copy["__parent"] = group_name
            lines.append(json.dumps(child_copy, separators=(",", ":")))
        write_func(full_path, "\n".join(lines) + ("\n" if lines else ""))
        for child in children:
            if child.get("class") == "SimGroup":
                _write_group(child, path_segments + [group_name])

    _ensure_pid(scene_root)
    root_line = {k: v for k, v in scene_root.items() if k != "childs"}
    write_func(f"{base_main_path}/items.level.json",
               json.dumps(root_line, separators=(",", ":")) + "\n")
    _write_group(scene_root, [])


# ---------------------------------------------------------------------------
# Image helpers
# ---------------------------------------------------------------------------

def _heightmap_visual_png(heightmap_m: np.ndarray) -> bytes:
    """16-bit greyscale PNG for the world editor's heightmap display."""
    min_m = heightmap_m.min()
    max_m = heightmap_m.max()
    rng = max(float(max_m - min_m), 1e-6)
    quant = ((heightmap_m - min_m) / rng * 65535).clip(0, 65535).astype("<u2")
    # Y-flip: .png row 0 = top (north), BeamNG editor expects this orientation
    img = Image.fromarray(quant[::-1, :], mode="I;16")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def _flat_terrain_png(size: int = 1024, rgb: tuple[int, int, int] = (90, 110, 70)) -> bytes:
    buf = io.BytesIO()
    Image.new("RGB", (size, size), rgb).save(buf, format="PNG")
    return buf.getvalue()


def _solid_preview_png(size: int = 256) -> bytes:
    buf = io.BytesIO()
    Image.new("RGB", (size, size), (40, 60, 90)).save(buf, format="PNG")
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Top-level export
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class LevelPackage:
    zip_path: Path
    level_name: str
    spawn_xyz: tuple[float, float, float]
    terrain_min_m: float
    terrain_max_m: float


def write_level_package(
    *,
    level_name: str,
    heightmap_m: np.ndarray,
    side_m: float,
    out_dir: Path,
    layer_map: np.ndarray | None = None,
    material_names: list[str] | None = None,
    terrain_png_bytes: bytes | None = None,
    buildings: Sequence[BuildingPlacement] = (),
    foliage: FoliageResult | None = None,
    decal_roads: Sequence[DecalRoad] = (),
    splat: SplatResult | None = None,
) -> LevelPackage:
    out_dir.mkdir(parents=True, exist_ok=True)
    zip_path = out_dir / f"{level_name}.zip"

    size_px = heightmap_m.shape[0]
    if heightmap_m.shape[1] != size_px:
        raise ValueError("heightmap must be square")

    # Resolve material list and layer map
    if splat is not None:
        materials = [f"mat_{l.cls.key}" for l in splat.layers]
        remap = np.zeros(256, dtype=np.uint8)
        for arr_idx, layer in enumerate(splat.layers):
            remap[layer.cls.id] = arr_idx
        layer_map = remap[splat.layer_index_map]
    elif material_names is not None:
        materials = list(material_names)
    else:
        materials = ["DefaultMaterial"]

    # Write .ter binary
    ter_path = out_dir / "_tmp_theTerrain.ter"
    t_min, t_max = write_ter(heightmap_m, ter_path, layer_map=layer_map, material_names=materials)
    ter_bytes = ter_path.read_bytes()
    ter_path.unlink()

    # Optional WaterPlane (opt-in via env var — WaterPlane strict field set
    # causes load failures unless we ship a fully validated field set)
    water_z: float | None = None
    if (os.environ.get("MAPNG_WATER_PLANE") == "1"
            and splat is not None
            and splat.layer_index_map is not None):
        try:
            from mapng_ai.pipeline.classmap import CLASSES as _C
            water_id = next((c.id for c in _C.values() if c.key == "water"), None)
            if water_id is not None:
                hmap = heightmap_m
                lmap = splat.layer_index_map[::-1, :]
                if lmap.shape == hmap.shape:
                    water_pixels = hmap[lmap == water_id]
                    if water_pixels.size > 50:
                        water_z = float(np.median(water_pixels)) - 0.10
        except Exception:
            water_z = None

    # Spawn at terrain centre, 3 m above surface
    centre_h = float(heightmap_m[size_px // 2, size_px // 2])
    spawn_xyz = (0.0, 0.0, centre_h + 3.0)

    base = f"levels/{level_name}"
    files: list[tuple[str, bytes]] = []

    def w(path: str, data: bytes | str) -> None:
        if isinstance(data, str):
            data = data.encode("utf-8")
        files.append((path, data))

    # ------------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------------
    w(f"{base}/info.json", json.dumps(_info_json(level_name, side_m), indent=2))

    foreign_levels: set[str] = set()
    for b in buildings:
        rel = b.asset.shape_relpath
        if rel.startswith("levels/") and "/" in rel[len("levels/"):]:
            foreign_levels.add(rel[len("levels/"):].split("/", 1)[0])
    if foliage:
        for t in foliage.trees:
            rel = t.shape_relpath
            if rel.startswith("levels/") and "/" in rel[len("levels/"):]:
                foreign_levels.add(rel[len("levels/"):].split("/", 1)[0])
    foreign_levels.discard(level_name)
    w(f"{base}/mainLevel.lua", _main_level_lua(level_name, sorted(foreign_levels)))
    w(f"{base}/preview.png", _solid_preview_png())

    # ------------------------------------------------------------------
    # Terrain binary + JSON descriptor
    # ------------------------------------------------------------------
    w(f"{base}/theTerrain.ter", ter_bytes)
    w(f"{base}/theTerrain.terrain.json",
      json.dumps(_terrain_json(level_name, size_px, side_m, materials), indent=2))
    w(f"{base}/theTerrain.terrainheightmap.png", _heightmap_visual_png(heightmap_m))

    # ------------------------------------------------------------------
    # Terrain materials
    # ------------------------------------------------------------------
    w(f"{base}/art/terrains/main.materials.json",
      json.dumps(_terrain_materials_json(level_name, side_m, splat), indent=2))

    # Per-class PBR diffuse + optional normal/roughness + opacity mask
    if splat is not None:
        for layer in splat.layers:
            key = layer.cls.key
            de = layer.diffuse_path.suffix.lower()
            w(f"{base}/art/terrains/diffuse_{key}{de}", layer.diffuse_path.read_bytes())
            # Opacity PNGs are kept in the zip for the world editor; they are NOT
            # referenced in materials.json (blending is encoded in .ter layerMap).
            w(f"{base}/art/terrains/opacity_{key}.png", layer.opacity_path.read_bytes())
            if layer.normal_path is not None:
                ne = layer.normal_path.suffix.lower()
                w(f"{base}/art/terrains/normal_{key}{ne}", layer.normal_path.read_bytes())
            if layer.roughness_path is not None:
                re_ = layer.roughness_path.suffix.lower()
                w(f"{base}/art/terrains/rough_{key}{re_}", layer.roughness_path.read_bytes())

    # Base diffuse texture (single large image that covers the whole terrain)
    if terrain_png_bytes is not None:
        w(f"{base}/art/terrains/terrain.png", terrain_png_bytes)
    elif splat is not None:
        w(f"{base}/art/terrains/terrain.png", splat.combined_diffuse_path.read_bytes())
    else:
        w(f"{base}/art/terrains/terrain.png", _flat_terrain_png())

    # ------------------------------------------------------------------
    # Road textures + materials
    # ------------------------------------------------------------------
    if decal_roads:
        w(f"{base}/art/road/road_decal.png", write_road_decal_texture().read_bytes())
        w(f"{base}/art/road/drive_decal.png", write_drive_decal_texture().read_bytes())
        w(f"{base}/art/road/main.materials.json",
          json.dumps(_road_materials_json(level_name), indent=2))

    # ------------------------------------------------------------------
    # Building shapes
    # ------------------------------------------------------------------
    from mapng_ai.assets.library import building_library_fs_path
    if buildings:
        seen: set[str] = set()
        for b in buildings:
            rel = b.asset.shape_relpath
            if rel in seen:
                continue
            seen.add(rel)
            if rel.startswith("levels/"):
                continue
            lib_fs = building_library_fs_path(rel)
            if lib_fs is not None:
                w(f"{base}/{rel}", lib_fs.read_bytes())
                continue
            cache_path, fallback_rel = write_pitched_dae(
                b.asset.type_label.replace("_meshy", "")
            )
            w(f"{base}/{rel if rel.endswith('.dae') else fallback_rel}",
              cache_path.read_bytes())

    # ------------------------------------------------------------------
    # Foliage shapes (trees + hedges)
    # ------------------------------------------------------------------
    if foliage and (foliage.trees or foliage.hedges):
        from mapng_ai.assets.library import tree_library
        seen_tree: set[str] = set()
        if foliage.trees:
            tree_lib = tree_library()
            lib_lookup: dict[str, Path] = {}
            for entries in tree_lib.values():
                for e in entries:
                    lib_lookup[e.rel_path] = e.fs_path
            for t in foliage.trees:
                rel = t.shape_relpath
                if rel in seen_tree:
                    continue
                seen_tree.add(rel)
                if rel.startswith("levels/"):
                    continue
                if rel in lib_lookup:
                    w(f"{base}/{rel}", lib_lookup[rel].read_bytes())
                else:
                    placeholder_path, _ = write_tree_dae()
                    w(f"{base}/{rel}", placeholder_path.read_bytes())
        if foliage.hedges:
            mats = {getattr(h, "material", "hedge") for h in foliage.hedges}
            if "hedge" in mats:
                p, _ = write_hedge_dae()
                w(f"{base}/art/shapes/foliage/hedge.dae", p.read_bytes())
            if "wall" in mats:
                p, _ = write_wall_dae()
                w(f"{base}/art/shapes/foliage/wall.dae", p.read_bytes())
            if "fence" in mats:
                p, _ = write_fence_dae()
                w(f"{base}/art/shapes/foliage/fence.dae", p.read_bytes())
            if "gate" in mats:
                p, _ = write_gate_dae()
                w(f"{base}/art/shapes/foliage/gate.dae", p.read_bytes())

    # ------------------------------------------------------------------
    # Scene graph (NDJSON items.level.json files)
    # ------------------------------------------------------------------
    scene_root = _mission_group(
        level_name, side_m, size_px, t_min, t_max, spawn_xyz,
        buildings, foliage, decal_roads, water_z=water_z,
    )
    _emit_ndjson_tree(scene_root, f"{base}/main", w)

    # ------------------------------------------------------------------
    # Build the ZIP
    # ------------------------------------------------------------------
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for path, data in files:
            zf.writestr(path, data)

    return LevelPackage(
        zip_path=zip_path,
        level_name=level_name,
        spawn_xyz=spawn_xyz,
        terrain_min_m=t_min,
        terrain_max_m=t_max,
    )
